apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acr-external-secret
  annotations:
    "external-secrets.io/delete-on-resource-deletion": "true"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: azure-keyvault-secret-store
    kind: ClusterSecretStore
  target:
    name: acr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: acr-dockerconfigjson
